package org.hisp.dhis.rules.models;

import com.google.auto.value.AutoValue;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

@AutoValue
public abstract class RuleActionDisplayText {
    public static final String LOCATION_FEEDBACK_WIDGET = "feedback";
    public static final String LOCATION_INDICATOR_WIDGET = "indicators";

    /**
     * @return a static content which will
     * be shown to the user.
     */
    @Nonnull
    public abstract String content();

    /**
     * @return dynamic data which can be potentially
     * generated by the RuleEngine.
     */
    @Nonnull
    public abstract String data();

    /**
     * @return location of where the result of this
     * action must be rendered: can be either 'feedback'
     * or 'program indicator' widget.
     */
    @Nonnull
    public abstract String location();

    @Nonnull
    public static RuleActionDisplayText createForFeedback(
            @Nullable String content, @Nullable String data) {
        if (content == null && data == null) {
            throw new IllegalArgumentException("Both content and data must not be null");
        }

        return new AutoValue_RuleActionDisplayText(content == null ? "" : content,
                data == null ? "" : data, LOCATION_FEEDBACK_WIDGET);
    }

    @Nonnull
    public static RuleActionDisplayText createForIndicators(
            @Nullable String content, @Nullable String data) {
        if (content == null && data == null) {
            throw new IllegalArgumentException("Both content and data must not be null");
        }

        return new AutoValue_RuleActionDisplayText(content == null ? "" : content,
                data == null ? "" : data, LOCATION_INDICATOR_WIDGET);
    }
}
