package org.hisp.dhis.rules.models;

public enum RuleActionType {
    DISPLAYTEXT,
    DISPLAYKEYVALUEPAIR,
    HIDEFIELD,
    HIDESECTION,
    ASSIGN,
    SHOWWARNING,
    WARNINGONCOMPLETE,
    SHOWERROR,
    ERRORONCOMPLETE,
    CREATEEVENT,
    HIDEPROGRAMSTAGE
}