package org.hisp.dhis.android.sdk.persistence.preferences;

/**
 * @author Araz Abishov <araz.abishov.gsoc@gmail.com>.
 */
public enum ResourceType {
    DASHBOARDS_CONTENT, DASHBOARDS, INTERPRETATIONS, USERS, OPTIONSETS, PROGRAMS, PROGRAM,
    TRACKEDENTITYATTRIBUTES, CONSTANTS, ASSIGNEDPROGRAMS, PROGRAMRULES, PROGRAMRULEVARIABLES,
    PROGRAMRULEACTIONS, RELATIONSHIPTYPES, EVENTS, EVENT, TRACKEDENTITYINSTANCE, ENROLLMENT,
    ENROLLMENTS
}
