# Use displayXXX instead of XXX for Program and ProgramStage (ANDROSDK-1871)
# EyeSeeTea customization fix bug in migration script. Following SQLite doc
# https://sqlite.org/lang_altertable.html#caution

CREATE TABLE Program_NEW (_id INTEGER PRIMARY KEY AUTOINCREMENT, uid TEXT NOT NULL UNIQUE, code TEXT, name TEXT, displayName TEXT, created TEXT, lastUpdated TEXT, shortName TEXT, displayShortName TEXT, description TEXT, displayDescription TEXT, version INTEGER, onlyEnrollOnce INTEGER, displayEnrollmentDateLabel TEXT, displayIncidentDate INTEGER, displayIncidentDateLabel TEXT, registration INTEGER, selectEnrollmentDatesInFuture INTEGER, dataEntryMethod INTEGER, ignoreOverdueEvents INTEGER, selectIncidentDatesInFuture INTEGER, useFirstStageDuringRegistration INTEGER, displayFrontPageList INTEGER, programType TEXT, relatedProgram TEXT, trackedEntityType TEXT, categoryCombo TEXT, accessDataWrite INTEGER, expiryDays INTEGER, completeEventsExpiryDays INTEGER, expiryPeriodType TEXT, minAttributesRequiredToSearch INTEGER, maxTeiCountToReturn INTEGER, featureType TEXT, accessLevel TEXT, color TEXT, icon TEXT, displayEnrollmentLabel TEXT, displayFollowUpLabel TEXT, displayOrgUnitLabel TEXT, displayRelationshipLabel TEXT, displayNoteLabel TEXT, displayTrackedEntityAttributeLabel TEXT, displayProgramStageLabel TEXT, displayEventLabel TEXT, FOREIGN KEY (trackedEntityType) REFERENCES TrackedEntityType (uid) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED, FOREIGN KEY (categoryCombo) REFERENCES CategoryCombo (uid) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED);
INSERT INTO Program_NEW (_id, uid, code, name, displayName, created, lastUpdated, shortName, displayShortName, description, displayDescription, version, onlyEnrollOnce, displayEnrollmentDateLabel, displayIncidentDate, displayIncidentDateLabel, registration, selectEnrollmentDatesInFuture, dataEntryMethod, ignoreOverdueEvents, selectIncidentDatesInFuture, useFirstStageDuringRegistration, displayFrontPageList, programType, relatedProgram, trackedEntityType, categoryCombo, accessDataWrite, expiryDays, completeEventsExpiryDays, expiryPeriodType, minAttributesRequiredToSearch, maxTeiCountToReturn, featureType, accessLevel, color, icon, displayEnrollmentLabel, displayFollowUpLabel, displayOrgUnitLabel, displayRelationshipLabel, displayNoteLabel, displayTrackedEntityAttributeLabel, displayProgramStageLabel, displayEventLabel) SELECT _id, uid, code, name, displayName, created, lastUpdated, shortName, displayShortName, description, displayDescription, version, onlyEnrollOnce, enrollmentDateLabel AS displayEnrollmentDateLabel, displayIncidentDate, incidentDateLabel AS displayIncidentDateLabel, registration, selectEnrollmentDatesInFuture, dataEntryMethod, ignoreOverdueEvents, selectIncidentDatesInFuture, useFirstStageDuringRegistration, displayFrontPageList, programType, relatedProgram, trackedEntityType, categoryCombo, accessDataWrite, expiryDays, completeEventsExpiryDays, expiryPeriodType, minAttributesRequiredToSearch, maxTeiCountToReturn, featureType, accessLevel, color, icon, enrollmentLabel AS displayEnrollmentLabel, followUpLabel AS displayFollowUpLabel, orgUnitLabel AS displayOrgUnitLabel, relationshipLabel AS displayRelationshipLabel, noteLabel AS displayNoteLabel, trackedEntityAttributeLabel AS displayTrackedEntityAttributeLabel, programStageLabel AS displayProgramStageLabel, eventLabel AS displayEventLabel FROM Program;
DROP TABLE IF EXISTS Program;
ALTER TABLE Program_NEW RENAME TO Program;


CREATE TABLE ProgramStage_NEW (_id INTEGER PRIMARY KEY AUTOINCREMENT, uid TEXT NOT NULL UNIQUE, code TEXT, name TEXT, displayName TEXT, created TEXT, lastUpdated TEXT, displayExecutionDateLabel TEXT, allowGenerateNextVisit INTEGER, validCompleteOnly INTEGER, reportDateToUse TEXT, openAfterEnrollment INTEGER, repeatable INTEGER, formType TEXT, displayGenerateEventBox INTEGER, generatedByEnrollmentDate INTEGER, autoGenerateEvent INTEGER, sortOrder INTEGER, hideDueDate INTEGER, blockEntryForm INTEGER, minDaysFromStart INTEGER, standardInterval INTEGER, program TEXT NOT NULL, periodType TEXT, accessDataWrite INTEGER, remindCompleted INTEGER, description TEXT, displayDescription TEXT, featureType TEXT, color TEXT, icon TEXT, enableUserAssignment INTEGER, displayDueDateLabel TEXT, validationStrategy TEXT, displayProgramStageLabel TEXT, displayEventLabel TEXT, FOREIGN KEY (program) REFERENCES Program (uid) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED);
INSERT INTO ProgramStage_NEW (_id, uid, code, name, displayName, created, lastUpdated, displayExecutionDateLabel, allowGenerateNextVisit, validCompleteOnly, reportDateToUse, openAfterEnrollment, repeatable, formType, displayGenerateEventBox, generatedByEnrollmentDate, autoGenerateEvent, sortOrder, hideDueDate, blockEntryForm, minDaysFromStart, standardInterval, program, periodType, accessDataWrite, remindCompleted, description, displayDescription, featureType, color, icon, enableUserAssignment, displayDueDateLabel, validationStrategy, displayProgramStageLabel, displayEventLabel) SELECT _id, uid, code, name, displayName, created, lastUpdated, executionDateLabel AS displayExecutionDateLabel, allowGenerateNextVisit, validCompleteOnly, reportDateToUse, openAfterEnrollment, repeatable, formType, displayGenerateEventBox, generatedByEnrollmentDate, autoGenerateEvent, sortOrder, hideDueDate, blockEntryForm, minDaysFromStart, standardInterval, program, periodType, accessDataWrite, remindCompleted, description, displayDescription, featureType, color, icon, enableUserAssignment, dueDateLabel AS displayDueDateLabel, validationStrategy, programStageLabel AS displayProgramStageLabel, eventLabel AS displayEventLabel FROM ProgramStage;
DROP TABLE IF EXISTS ProgramStage
ALTER TABLE ProgramStage_NEW RENAME TO ProgramStage;
