CREATE TABLE EventDataFilter (_id INTEGER PRIMARY KEY AUTOINCREMENT, eventFilter TEXT, dataItem TEXT, le TEXT, ge TEXT, gt TEXT, lt TEXT, eq TEXT, inProperty TEXT, like TEXT, dateFilter TEXT, FOREIGN KEY (eventFilter) REFERENCES EventFilter (uid) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED, FOREIGN KEY (dataItem) REFERENCES DataElement (uid) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE AttributeValueFilter (_id INTEGER PRIMARY KEY AUTOINCREMENT, trackedEntityInstanceFilter TEXT, attribute TEXT, sw TEXT, ew TEXT, le TEXT, ge TEXT, gt TEXT, lt TEXT, eq TEXT, inProperty TEXT, like TEXT, dateFilter TEXT, FOREIGN KEY (trackedEntityInstanceFilter) REFERENCES TrackedEntityInstanceFilter (uid) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED, FOREIGN KEY (attribute) REFERENCES TrackedEntityAttribute (uid) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE ProgramStageWorkingListEventDataFilter (_id INTEGER PRIMARY KEY AUTOINCREMENT, programStageWorkingList TEXT, dataItem TEXT, le TEXT, ge TEXT, gt TEXT, lt TEXT, eq TEXT, inProperty TEXT, like TEXT, dateFilter TEXT, FOREIGN KEY (programStageWorkingList) REFERENCES ProgramStageWorkingList (uid) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED, FOREIGN KEY (dataItem) REFERENCES DataElement (uid) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE ProgramStageWorkingListAttributeValueFilter (_id INTEGER PRIMARY KEY AUTOINCREMENT, programStageWorkingList TEXT, attribute TEXT, sw TEXT, ew TEXT, le TEXT, ge TEXT, gt TEXT, lt TEXT, eq TEXT, inProperty TEXT, like TEXT, dateFilter TEXT, FOREIGN KEY (programStageWorkingList) REFERENCES ProgramStageWorkingList (uid) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED, FOREIGN KEY (attribute) REFERENCES TrackedEntityAttribute (uid) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED);
INSERT INTO EventDataFilter (_id, eventFilter, dataItem, le, ge, gt, lt, eq, inProperty, like, dateFilter) SELECT _id, eventFilter, dataItem, le, ge, gt, lt, eq, inProperty, like, dateFilter FROM ItemFilter WHERE eventFilter IS NOT NULL AND dataItem IS NOT NULL;
INSERT INTO AttributeValueFilter (_id, trackedEntityInstanceFilter, attribute, sw, ew, le, ge, gt, lt, eq, inProperty, like, dateFilter) SELECT _id, trackedEntityInstanceFilter, attribute, sw, ew, le, ge, gt, lt, eq, inProperty, like, dateFilter FROM ItemFilter WHERE trackedEntityInstanceFilter IS NOT NULL AND attribute IS NOT NULL;
INSERT INTO ProgramStageWorkingListEventDataFilter (_id, programStageWorkingList, dataItem, le, ge, gt, lt, eq, inProperty, like, dateFilter) SELECT _id, programStageWorkingList, dataItem, le, ge, gt, lt, eq, inProperty, like, dateFilter FROM ItemFilter WHERE programStageWorkingList IS NOT NULL AND dataItem IS NOT NULL;
INSERT INTO ProgramStageWorkingListAttributeValueFilter (_id, programStageWorkingList, attribute, sw, ew, le, ge, gt, lt, eq, inProperty, like, dateFilter) SELECT _id, programStageWorkingList, attribute, sw, ew, le, ge, gt, lt, eq, inProperty, like, dateFilter FROM ItemFilter WHERE programStageWorkingList IS NOT NULL AND attribute IS NOT NULL;
DROP TABLE ItemFilter;
