# Repair pending NUMBER and INTEGER values the server rejects (ANDROSDK-2391).
# NUMBER: trim spaces, remove the plus sign (+4 -> 4), add the missing zero before the decimal point (-.62 -> -0.62),
# remove a trailing decimal point (5. -> 5) and leading zeros (007 -> 7). Values that still do not match
# the server pattern cannot be repaired and are discarded.
# INTEGER types: remove the plus sign (+4 -> 4). INTEGER and INTEGER_ZERO_OR_POSITIVE: replace negative zero (-0 -> 0).
# DataValue
UPDATE DataValue SET value = trim(value) WHERE syncState != 'SYNCED' AND dataElement IN (SELECT uid FROM DataElement WHERE valueType = 'NUMBER') AND value != trim(value);
UPDATE DataValue SET value = substr(value, 2) WHERE syncState != 'SYNCED' AND dataElement IN (SELECT uid FROM DataElement WHERE valueType IN ('NUMBER', 'INTEGER', 'INTEGER_POSITIVE', 'INTEGER_NEGATIVE', 'INTEGER_ZERO_OR_POSITIVE')) AND value GLOB '+*';
UPDATE DataValue SET value = '0' WHERE syncState != 'SYNCED' AND dataElement IN (SELECT uid FROM DataElement WHERE valueType IN ('INTEGER', 'INTEGER_ZERO_OR_POSITIVE')) AND value = '-0';
UPDATE DataValue SET value = substr(value, 1, (substr(value, 1, 1) = '-')) || '0' || substr(value, (substr(value, 1, 1) = '-') + 1) WHERE syncState != 'SYNCED' AND dataElement IN (SELECT uid FROM DataElement WHERE valueType = 'NUMBER') AND substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '.[0-9]*';
UPDATE DataValue SET value = substr(value, 1, length(value) - 1) WHERE syncState != 'SYNCED' AND dataElement IN (SELECT uid FROM DataElement WHERE valueType = 'NUMBER') AND substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '*[0-9].' AND substr(substr(value, (substr(value, 1, 1) = '-') + 1), 1, length(substr(value, (substr(value, 1, 1) = '-') + 1)) - 1) NOT GLOB '*[^0-9]*';
UPDATE DataValue SET value = substr(value, 1, (substr(value, 1, 1) = '-')) || CASE WHEN ltrim(substr(value, (substr(value, 1, 1) = '-') + 1), '0') = '' OR ltrim(substr(value, (substr(value, 1, 1) = '-') + 1), '0') GLOB '.*' THEN '0' ELSE '' END || ltrim(substr(value, (substr(value, 1, 1) = '-') + 1), '0') WHERE syncState != 'SYNCED' AND dataElement IN (SELECT uid FROM DataElement WHERE valueType = 'NUMBER') AND substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '0[0-9]*';
DELETE FROM DataValue WHERE syncState != 'SYNCED' AND dataElement IN (SELECT uid FROM DataElement WHERE valueType = 'NUMBER') AND value != '' AND (substr(value, (substr(value, 1, 1) = '-') + 1) = '' OR substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '*[^0-9.]*' OR substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '.*' OR substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '*.' OR substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '0[0-9]*' OR substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '*.*.*');
# TrackedEntityDataValue
UPDATE TrackedEntityDataValue SET value = trim(value) WHERE syncState != 'SYNCED' AND dataElement IN (SELECT uid FROM DataElement WHERE valueType = 'NUMBER') AND value != trim(value);
UPDATE TrackedEntityDataValue SET value = substr(value, 2) WHERE syncState != 'SYNCED' AND dataElement IN (SELECT uid FROM DataElement WHERE valueType IN ('NUMBER', 'INTEGER', 'INTEGER_POSITIVE', 'INTEGER_NEGATIVE', 'INTEGER_ZERO_OR_POSITIVE')) AND value GLOB '+*';
UPDATE TrackedEntityDataValue SET value = '0' WHERE syncState != 'SYNCED' AND dataElement IN (SELECT uid FROM DataElement WHERE valueType IN ('INTEGER', 'INTEGER_ZERO_OR_POSITIVE')) AND value = '-0';
UPDATE TrackedEntityDataValue SET value = substr(value, 1, (substr(value, 1, 1) = '-')) || '0' || substr(value, (substr(value, 1, 1) = '-') + 1) WHERE syncState != 'SYNCED' AND dataElement IN (SELECT uid FROM DataElement WHERE valueType = 'NUMBER') AND substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '.[0-9]*';
UPDATE TrackedEntityDataValue SET value = substr(value, 1, length(value) - 1) WHERE syncState != 'SYNCED' AND dataElement IN (SELECT uid FROM DataElement WHERE valueType = 'NUMBER') AND substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '*[0-9].' AND substr(substr(value, (substr(value, 1, 1) = '-') + 1), 1, length(substr(value, (substr(value, 1, 1) = '-') + 1)) - 1) NOT GLOB '*[^0-9]*';
UPDATE TrackedEntityDataValue SET value = substr(value, 1, (substr(value, 1, 1) = '-')) || CASE WHEN ltrim(substr(value, (substr(value, 1, 1) = '-') + 1), '0') = '' OR ltrim(substr(value, (substr(value, 1, 1) = '-') + 1), '0') GLOB '.*' THEN '0' ELSE '' END || ltrim(substr(value, (substr(value, 1, 1) = '-') + 1), '0') WHERE syncState != 'SYNCED' AND dataElement IN (SELECT uid FROM DataElement WHERE valueType = 'NUMBER') AND substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '0[0-9]*';
DELETE FROM TrackedEntityDataValue WHERE syncState != 'SYNCED' AND dataElement IN (SELECT uid FROM DataElement WHERE valueType = 'NUMBER') AND value != '' AND (substr(value, (substr(value, 1, 1) = '-') + 1) = '' OR substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '*[^0-9.]*' OR substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '.*' OR substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '*.' OR substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '0[0-9]*' OR substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '*.*.*');
# TrackedEntityAttributeValue
UPDATE TrackedEntityAttributeValue SET value = trim(value) WHERE syncState != 'SYNCED' AND trackedEntityAttribute IN (SELECT uid FROM TrackedEntityAttribute WHERE valueType = 'NUMBER') AND value != trim(value);
UPDATE TrackedEntityAttributeValue SET value = substr(value, 2) WHERE syncState != 'SYNCED' AND trackedEntityAttribute IN (SELECT uid FROM TrackedEntityAttribute WHERE valueType IN ('NUMBER', 'INTEGER', 'INTEGER_POSITIVE', 'INTEGER_NEGATIVE', 'INTEGER_ZERO_OR_POSITIVE')) AND value GLOB '+*';
UPDATE TrackedEntityAttributeValue SET value = '0' WHERE syncState != 'SYNCED' AND trackedEntityAttribute IN (SELECT uid FROM TrackedEntityAttribute WHERE valueType IN ('INTEGER', 'INTEGER_ZERO_OR_POSITIVE')) AND value = '-0';
UPDATE TrackedEntityAttributeValue SET value = substr(value, 1, (substr(value, 1, 1) = '-')) || '0' || substr(value, (substr(value, 1, 1) = '-') + 1) WHERE syncState != 'SYNCED' AND trackedEntityAttribute IN (SELECT uid FROM TrackedEntityAttribute WHERE valueType = 'NUMBER') AND substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '.[0-9]*';
UPDATE TrackedEntityAttributeValue SET value = substr(value, 1, length(value) - 1) WHERE syncState != 'SYNCED' AND trackedEntityAttribute IN (SELECT uid FROM TrackedEntityAttribute WHERE valueType = 'NUMBER') AND substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '*[0-9].' AND substr(substr(value, (substr(value, 1, 1) = '-') + 1), 1, length(substr(value, (substr(value, 1, 1) = '-') + 1)) - 1) NOT GLOB '*[^0-9]*';
UPDATE TrackedEntityAttributeValue SET value = substr(value, 1, (substr(value, 1, 1) = '-')) || CASE WHEN ltrim(substr(value, (substr(value, 1, 1) = '-') + 1), '0') = '' OR ltrim(substr(value, (substr(value, 1, 1) = '-') + 1), '0') GLOB '.*' THEN '0' ELSE '' END || ltrim(substr(value, (substr(value, 1, 1) = '-') + 1), '0') WHERE syncState != 'SYNCED' AND trackedEntityAttribute IN (SELECT uid FROM TrackedEntityAttribute WHERE valueType = 'NUMBER') AND substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '0[0-9]*';
DELETE FROM TrackedEntityAttributeValue WHERE syncState != 'SYNCED' AND trackedEntityAttribute IN (SELECT uid FROM TrackedEntityAttribute WHERE valueType = 'NUMBER') AND value != '' AND (substr(value, (substr(value, 1, 1) = '-') + 1) = '' OR substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '*[^0-9.]*' OR substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '.*' OR substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '*.' OR substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '0[0-9]*' OR substr(value, (substr(value, 1, 1) = '-') + 1) GLOB '*.*.*');
