name: Benchmark

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        type: string
        description: 'DHIS2 SDK version (default to "current")'
      server_url:
        type: string
        description: 'Server url (default to "demo")'
      username:
        type: string
        description: 'Username (default to "android")'
      password:
        type: string
        description: 'Password (default to "Android123")'

jobs:
  publish:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: 'gradle'
      - name: Change wrapper permission
        run: chmod +x ./gradlew

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run benchmark
        run: |
          python -u ./scripts/benchmark.py device_logs.md
          cat device_logs.md > $GITHUB_STEP_SUMMARY
        env:
          BROWSERSTACK_USR: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_PSW: ${{ secrets.BROWSERSTACK_PASSWORD }}
          SDK_VERSION: ${{ inputs.sdk_version }}
          BENCHMARK_SERVER_URL: ${{ inputs.server_url }}
          BENCHMARK_USERNAME: ${{ inputs.username }}
          BENCHMARK_PASSWORD: ${{ inputs.password }}
