on:
  workflow_dispatch

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: 'gradle'
      - name: Change wrapper permission
        run: chmod +x ./gradlew

      - name: Publish Snapshot
        if: github.ref_name != 'main' && github.ref_name != 'master'
        run: ./gradlew :core:publishToSonatype
        env:
          NEXUS_USERNAME: ${{ secrets.SONATYPE_OSSRH_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.SONATYPE_OSSRH_PASSWORD }}

      - name: Publish Release
        if: github.ref_name == 'main' || github.ref_name == 'master'
        run: ./gradlew :core:publishToSonatype closeAndReleaseSonatypeStagingRepository -PremoveSnapshotSuffix
        env:
          NEXUS_USERNAME: ${{ secrets.SONATYPE_OSSRH_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.SONATYPE_OSSRH_PASSWORD }}
          SIGNING_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
          SIGNING_PASSWORD: ${{ secrets.PGP_PASSPHRASE }}
