name: Publish release

on:
  workflow_dispatch

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: 'gradle'
      - name: Change wrapper permission
        run: chmod +x ./gradlew

      - name: Publish Maven
        run: ./.github/workflows/scripts/publish-maven.sh
        env:
          NEXUS_USERNAME: ${{ secrets.SONATYPE_OSSRH_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.SONATYPE_OSSRH_PASSWORD }}
          SIGNING_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
          SIGNING_PASSWORD: ${{ secrets.PGP_PASSPHRASE }}
