#!/usr/bin/env bash

#
#  Copyright (c) 2004-2024, University of Oslo
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  Redistributions of source code must retain the above copyright notice, this
#  list of conditions and the following disclaimer.
#
#  Redistributions in binary form must reproduce the above copyright notice,
#  this list of conditions and the following disclaimer in the documentation
#  and/or other materials provided with the distribution.
#  Neither the name of the HISP project nor the names of its contributors may
#  be used to endorse or promote products derived from this software without
#  specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
#  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
#  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
#  ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
#  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
#  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#  This script ensures that Git commit messages include the current branch name (in uppercase) at the beginning,
#  unless the branch is excluded (e.g., `master` or `develop`) or already mentioned in the commit message.

if [ -z "$EXCLUDED_BRANCHES" ]; then
  EXCLUDED_BRANCHES=(master develop)
fi

CURRENT_BRANCH=$(git symbolic-ref --short HEAD)
CURRENT_BRANCH="${CURRENT_BRANCH##*/}"
CURRENT_BRANCH=$(echo "$CURRENT_BRANCH" | tr '[:lower:]' '[:upper:]')
BRANCH_EXCLUDED=$(printf "%s\n" "${EXCLUDED_BRANCHES[@]}" | grep -c "^$CURRENT_BRANCH$")
BRANCH_IN_COMMIT=$(grep -c "\[$CURRENT_BRANCH\]" "$1")

if [ -n "$CURRENT_BRANCH" ] && ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then
  sed -i.bak -e "1s/^/[$CURRENT_BRANCH] /" "$1"
fi